name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand and evaluate your request.

  - type: checkboxes
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions for similar feature requests
          required: true
        - label: I have reviewed the project roadmap to see if this is already planned
          required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: What feature would you like to be added?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem/Use Case
      description: What problem does this feature solve? What workflow would it improve?
      placeholder: Explain the problem this feature would solve or the workflow it would improve
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Alternative solutions or features you've considered
      placeholder: What alternatives have you considered?

  - type: dropdown
    attributes:
      label: Feature Category
      description: Which area of the tool does this feature relate to?
      options:
        - Interactive Workflow
        - Tool Detection
        - Conflict Analysis
        - Reporting/Output
        - Configuration
        - CLI Interface
        - API/Automation
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority/Impact
      description: How would you rate the importance of this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significantly impacts usability
        - Critical - Blocking current workflows

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context, mockups, examples, or references
      placeholder: Add any other context, screenshots, or examples here

  - type: checkboxes
    attributes:
      label: Implementation
      options:
        - label: I would be interested in implementing this feature
        - label: I would be willing to help test this feature